<a href="https://colab.research.google.com/github/abdhsn8/Saad/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import scipy.io as mp
from keras.utils import np_utils
import time
start_time = time.time()
# your code
import numpy 
import keras
from keras.datasets import imdb
from keras.models import Sequential
from keras.utils import np_utils
from keras.layers import Dense, Activation, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import models
from keras import layers
from keras import optimizers
from keras import losses
from keras import metrics
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score, recall_score, classification_report

In [113]:
data1 = numpy.loadtxt("qsnonqs.csv", delimiter=",")
data = data1[:, :108]
y = data1[:, 108:111]
rows = len(y)
columns = len(y[0])
print (rows)
print (columns)
print (y)

3775
3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [114]:
class TimingCallback(keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.starttime = time()

    def on_train_end(self, logs={}):
        self.time = (time() - self.starttime)
data_3d = data.reshape(3775, 1, 9, 12)

X_train, X_test, y_train, y_test = train_test_split(data_3d, y, test_size=0.25)

In [115]:
# L2 normalize data_3d along rows
# Our vectorized labels
#y_train = numpy.asarray(y_train).astype('float32').reshape((-1,1))
#y_test = numpy.asarray(y_test).astype('float32').reshape((-1,1))
x = np_utils.normalize(data_3d, -1, 1)
x.shape
rmslr = 0.001
epoch = 100
model = Sequential()

In [116]:
# first convolution
model.add(Conv2D(50, kernel_size=(1, 9), padding='valid', activation='relu', input_shape=(1, 9, 12),data_format='channels_first'))

# second convolution and maxpooling layer
model.add(Conv2D(20, kernel_size=(1, 4), padding='valid', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2), data_format='channels_first'))  # dim_ordering="th"))

# third convolution and maxpooling layer
#model.add(Conv2D(30, kernel_size=(2, 2), padding='valid',activation='relu'))
#model.add(MaxPooling2D(pool_size=(2, 2), data_format='channels_first'))#dim_ordering="th"))


# Flattening
model.add(Flatten())

# fully connected layers
model.add(Dense(128, activation='relu'))
# model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [117]:
rmslr = 0.001
epoch = 60
cb = TimingCallback()
rms = keras.optimizers.RMSprop(lr=rmslr, rho=0.9, epsilon=1e-6, decay=0.0)
sgd = keras.optimizers.SGD(lr=0.01, momentum=0.0, decay=0.0, nesterov=True)
adam = keras.optimizers.Adam(lr=0.001)
model.compile(loss=keras.losses.binary_crossentropy, optimizer=adam, metrics=['accuracy'])

In [118]:
history = model.fit(X_train, y_train, epochs=epoch, batch_size=50)
results = model.evaluate(X_test, y_test)
print(results)

Epoch 1/60
57/57 [==============================] - 1s 2ms/step - loss: 1.1433 - accuracy: 0.4726
Epoch 2/60
57/57 [==============================] - 0s 2ms/step - loss: 0.5458 - accuracy: 0.5413
Epoch 3/60
57/57 [==============================] - 0s 2ms/step - loss: 0.5414 - accuracy: 0.5815
Epoch 4/60
57/57 [==============================] - 0s 2ms/step - loss: 0.5362 - accuracy: 0.5666
Epoch 5/60
57/57 [==============================] - 0s 3ms/step - loss: 0.5121 - accuracy: 0.6157
Epoch 6/60
57/57 [==============================] - 0s 2ms/step - loss: 0.5096 - accuracy: 0.6026
Epoch 7/60
57/57 [==============================] - 0s 2ms/step - loss: 0.4873 - accuracy: 0.6210
Epoch 8/60
57/57 [==============================] - 0s 3ms/step - loss: 0.4881 - accuracy: 0.6116
Epoch 9/60
57/57 [==============================] - 0s 3ms/step - loss: 0.4758 - accuracy: 0.6423
Epoch 10/60
57/57 [==============================] - 0s 2ms/step - loss: 0.4790 - accuracy: 0.6235
Epoch 11/60
57/57 [